# coding: utf-8

"""
    Kerbside Curblr Api

    API for serving kerbside assets. Data is served in CurbLR format https://github.com/sharedstreets/curblr  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: tbd@ford.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.authority import Authority  # noqa: E501
from swagger_client.rest import ApiException


class TestAuthority(unittest.TestCase):
    """Authority unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuthority(self):
        """Test Authority"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.authority.Authority()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
